name: Deploy Node App

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t my-node-app:latest .

      # SSH into Server & Redeploy
      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            # Navigate to your project directory on the server (adjust path as needed)
            cd /path/to/your/project/directory || exit 1

            # Pull the latest changes (if you have git installed on the server)
            git pull origin main || exit 1

            # Rebuild and restart the Docker container
            docker build -t my-node-app:latest .
            docker stop my-node-app || true
            docker rm my-node-app || true
            docker run -d -p 3000:3000 --name my-node-app my-node-app:latest
